#!/bin/bash

set -e -x -u
cd $GOPATH

# ensure gosub is installed (this will recompile it only if necessary)
# go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -app github.com/cloudfoundry-incubator/guardian-cni-adapter/... \
    -app github.com/containernetworking/cni/plugins/meta/flannel \
    -app github.com/containernetworking/cni/plugins/main/bridge \
    -app github.com/containernetworking/cni/plugins/ipam/host-local

  gosub list \
      -test acceptance

  gosub list \
    -app policy-server \
    -app cf-cli-plugin \
    -app github.com/vito/gosub

  gosub list \
    -test policy-server/... \
    -test cf-cli-plugin/...

} > /tmp/packages

cat /tmp/packages | xargs gosub sync
